print("SHINDYZP_220511004_TIF22E")
print()
print("0.MENCARI NILAI BALOK")
print()
print("#SOAL, DIKETAHUI")
print("PANJANG BALOK = 50")
print("LEBAR   BALOK = 35")
print("TINGGI  BALOK = 55")
#VARIABEL BALOK
PANJANG_BALOK = 50
LEBAR_BALOK = 35
TINGGI_BALOK = 55
#RUMUS BALOK
LUAS_BALOK = 2 * (PANJANG_BALOK * LEBAR_BALOK) + (PANJANG_BALOK* TINGGI_BALOK) + (LEBAR_BALOK * TINGGI_BALOK)
VOLUME_BALOK = PANJANG_BALOK * LEBAR_BALOK * TINGGI_BALOK
print()
print ("#RUMUS") 
print ("LUAS    BALOK = 2 * (PANJANG BALOK * LEBAR BALOK) + (PANJANG BALOK* TINGGI BALOK) + (LEBAR BALOK * TINGGI BALOK)")
print ("VOLUME  BALOK = PANJANG BALOK * LEBAR BALOK * TINGGI BALOK")
print()
print("#HASIL")
#OUTPUT
print("LUAS    BALOK =", LUAS_BALOK)
print("VOLUME  BALOK =", VOLUME_BALOK)