print("SHINDYZP_220511004_TIF22E")
print()
print("1.MENCARI NILAI KUBUS")
print()
print("#SOAL, DIKETAHUI")
print("LEBAR   KUBUS   = 35")
print("TINGGI  KUBUS   = 55") 
#VARIABEL KUBUS
SISI_KUBUS = 63
#RUMUS KUBUS
LUAS_KUBUS = 6 * SISI_KUBUS
VOLUME_KUBUS = SISI_KUBUS * SISI_KUBUS * SISI_KUBUS
print()
print ("#RUMUS") 
print ("LUAS    KUBUS   = 6 * SISI KUBUS") 
print ("VOLUME  KUBUS   = SISI KUBUS * SISI KUBUS * SISI KUBUS") 
print()
print("#HASIL")
#OUTPUT
print("LUAS    KUBUS   =", LUAS_KUBUS)
print("VOLUME  KUBUS   =", VOLUME_KUBUS)