print("SHINDYZP_220511004_TIF22E")
print()
print("2.MENCARI NILAI TABUNG")
print()
print("#SOAL, DIKETAHUI")
print("JARI-JARI TABUNG   = 35")
print("TINGGI TABUNG      = 55") 
import math
#VARIABEL TABUNG
JARI_JARI_TABUNG= 10
TINGGI_TABUNG = 50
#RUMUS TABUNG
LUAS_TABUNG = (2 * math.pi * JARI_JARI_TABUNG) * JARI_JARI_TABUNG + TINGGI_TABUNG
VOLUME_TABUNG = math.pi * JARI_JARI_TABUNG * 2 * TINGGI_TABUNG
print()
print ("#RUMUS") 
print ("LUAS    TABUNG     = 2 * MATH.PI * JARI_JARI_TABUNG) * JARI_JARI_TABUNG + TINGGI_TABUNG")
print ("VOLUME  TABUNG     = MATH.PI * JARI_JARI_TABUNG * 2 * TINGGI_TABUNG")
print()
print("#HASIL")
#OUTPUT
print("LUAS TABUNG        =", LUAS_TABUNG)
print("VOLUME TABUNG      =", VOLUME_TABUNG)