print("SHINDYZP_220511004_TIF22E")
print()
print("5.MENCARI NILAI LIMAS SEGI4")
print()
print("#SOAL, DIKETAHUI")
print("SISI ALAS                    = 18")
print("TINGGI LIMAS                 = 15")
print("TINGGI SEGITIGA              = 16")
#VARIABEL_LIMASSEGI4
SISI_ALAS = 18
TINGGI_LIMAS = 15
TINGGI_SEGITIGA = 16
#RUMUS_LUAS
LUAS_PERMUKAAN = (SISI_ALAS ** 2) + 2 * SISI_ALAS * (TINGGI_LIMAS + TINGGI_SEGITIGA)
VOLUME = (SISI_ALAS ** 2 * TINGGI_LIMAS) / 3
print()
print('#RUMUS')
print ("LUAS PERMUKAAN LIMAS SEGI4   = (SISI_ALAS ** 2) + 2 * SISI_ALAS * (TINGGI_LIMAS + TINGGI_SEGITIGA)")
print ("VOLUME LIMAS SEGI4           = (SISI_ALAS ** 2 * TINGGI_LIMAS) / 3)")
print()
print("#HASIL") 
#OUTPUT
print("LUAS PERMUKAAN LIMAS SEGI4   = ", LUAS_PERMUKAAN)
print("VOLUME LIMAS SEGI4           = ", VOLUME)