print("SHINDYZP_220511004_TIF22E")
print()
print("7.MENCARI NILAI PRISMA SEGITIGA")
print()
print("#SOAL, DIKETAHUI")
print("SISI ALAS PRISMA SEGITIGA    = 22")
print("TINGGI PRISMA SEGI TIGA      = 40")
print("TINGGI LIMAS SEGI TIGA       = 60")
#VARIABEL_PRISMASEGITIGA
ALAS_SEGITIGA = 22
TINGGI_PRISMA = 40
TINGGI_SEGITIGA = 60
#RUMUS_PRISMASEGITIGA
LUAS_PERMUKAAN = (ALAS_SEGITIGA * TINGGI_PRISMA) + 2 * (0.5 * ALAS_SEGITIGA * TINGGI_SEGITIGA)
VOLUME =  0.5 * (ALAS_SEGITIGA * TINGGI_SEGITIGA * TINGGI_PRISMA)
print()
print("#RUMUS")
print ("LUAS_PERMUKAAN               = (ALAS_SEGITIGA * TINGGI_PRISMA) + 2 * (0.5 * ALAS_SEGITIGA * TINGGI_SEGITIGA)")
print("VOLUME                       =  0.5 * (ALAS_SEGITIGA * TINGGI_SEGITIGA * TINGGI_PRISMA)")
print()
print("#HASIL") 
#OUTPUT
print("LUAS PERMUKAAN PRISMA SEGI   = ", LUAS_PERMUKAAN)
print("VOLUME PRISMA SEGI TIGA      = ", VOLUME)